spring.application.name=AuthServices
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/translink_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port = 8081
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=TRACE
# JWT Security Settings
# Generate a 256-bit key: openssl rand -base64 32
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.cloud.config.enabled=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crimevault2@gmail.com
spring.mail.password=aszp yuva lvtn aqxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



